name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - streamlit == 1.35.0
    - pandas == 2.0.3
    - pytest == 8.2.1
    - anthropic == 0.26.1
    - jupyter == 1.0.0
    - langchain == 0.1.20
    - voyageai == 0.2.3
    - altair == 4.0
